/*
Copyright 2019 The Lijiao Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/fafucoder/sriov-crd/pkg/apis/sriov/v1"
	scheme "github.com/fafucoder/sriov-crd/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// VFsGetter has a method to return a VFInterface.
// A group's client should implement this interface.
type VFsGetter interface {
	VFs() VFInterface
}

// VFInterface has methods to work with VF resources.
type VFInterface interface {
	Create(*v1.VF) (*v1.VF, error)
	Update(*v1.VF) (*v1.VF, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.VF, error)
	List(opts metav1.ListOptions) (*v1.VFList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.VF, err error)
	VFExpansion
}

// vFs implements VFInterface
type vFs struct {
	client rest.Interface
}

// newVFs returns a VFs
func newVFs(c *KubeovnV1Client) *vFs {
	return &vFs{
		client: c.RESTClient(),
	}
}

// Get takes name of the vF, and returns the corresponding vF object, and an error if there is any.
func (c *vFs) Get(name string, options metav1.GetOptions) (result *v1.VF, err error) {
	result = &v1.VF{}
	err = c.client.Get().
		Resource("vfs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of VFs that match those selectors.
func (c *vFs) List(opts metav1.ListOptions) (result *v1.VFList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.VFList{}
	err = c.client.Get().
		Resource("vfs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested vFs.
func (c *vFs) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("vfs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a vF and creates it.  Returns the server's representation of the vF, and an error, if there is any.
func (c *vFs) Create(vF *v1.VF) (result *v1.VF, err error) {
	result = &v1.VF{}
	err = c.client.Post().
		Resource("vfs").
		Body(vF).
		Do().
		Into(result)
	return
}

// Update takes the representation of a vF and updates it. Returns the server's representation of the vF, and an error, if there is any.
func (c *vFs) Update(vF *v1.VF) (result *v1.VF, err error) {
	result = &v1.VF{}
	err = c.client.Put().
		Resource("vfs").
		Name(vF.Name).
		Body(vF).
		Do().
		Into(result)
	return
}

// Delete takes name of the vF and deletes it. Returns an error if one occurs.
func (c *vFs) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("vfs").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *vFs) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("vfs").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched vF.
func (c *vFs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.VF, err error) {
	result = &v1.VF{}
	err = c.client.Patch(pt).
		Resource("vfs").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
