/*
Copyright 2019 The Lijiao Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	sriovv1 "github.com/fafucoder/sriov-crd/pkg/apis/sriov/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSriovVFs implements SriovVFInterface
type FakeSriovVFs struct {
	Fake *FakeKubeovnV1
}

var sriovvfsResource = schema.GroupVersionResource{Group: "kubeovn.io", Version: "v1", Resource: "sriovvfs"}

var sriovvfsKind = schema.GroupVersionKind{Group: "kubeovn.io", Version: "v1", Kind: "SriovVF"}

// Get takes name of the sriovVF, and returns the corresponding sriovVF object, and an error if there is any.
func (c *FakeSriovVFs) Get(name string, options v1.GetOptions) (result *sriovv1.SriovVF, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(sriovvfsResource, name), &sriovv1.SriovVF{})
	if obj == nil {
		return nil, err
	}
	return obj.(*sriovv1.SriovVF), err
}

// List takes label and field selectors, and returns the list of SriovVFs that match those selectors.
func (c *FakeSriovVFs) List(opts v1.ListOptions) (result *sriovv1.SriovVFList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(sriovvfsResource, sriovvfsKind, opts), &sriovv1.SriovVFList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &sriovv1.SriovVFList{ListMeta: obj.(*sriovv1.SriovVFList).ListMeta}
	for _, item := range obj.(*sriovv1.SriovVFList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested sriovVFs.
func (c *FakeSriovVFs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(sriovvfsResource, opts))
}

// Create takes the representation of a sriovVF and creates it.  Returns the server's representation of the sriovVF, and an error, if there is any.
func (c *FakeSriovVFs) Create(sriovVF *sriovv1.SriovVF) (result *sriovv1.SriovVF, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(sriovvfsResource, sriovVF), &sriovv1.SriovVF{})
	if obj == nil {
		return nil, err
	}
	return obj.(*sriovv1.SriovVF), err
}

// Update takes the representation of a sriovVF and updates it. Returns the server's representation of the sriovVF, and an error, if there is any.
func (c *FakeSriovVFs) Update(sriovVF *sriovv1.SriovVF) (result *sriovv1.SriovVF, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(sriovvfsResource, sriovVF), &sriovv1.SriovVF{})
	if obj == nil {
		return nil, err
	}
	return obj.(*sriovv1.SriovVF), err
}

// Delete takes name of the sriovVF and deletes it. Returns an error if one occurs.
func (c *FakeSriovVFs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(sriovvfsResource, name), &sriovv1.SriovVF{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSriovVFs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(sriovvfsResource, listOptions)

	_, err := c.Fake.Invokes(action, &sriovv1.SriovVFList{})
	return err
}

// Patch applies the patch and returns the patched sriovVF.
func (c *FakeSriovVFs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *sriovv1.SriovVF, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(sriovvfsResource, name, pt, data, subresources...), &sriovv1.SriovVF{})
	if obj == nil {
		return nil, err
	}
	return obj.(*sriovv1.SriovVF), err
}
