/*
Copyright 2019 The Lijiao Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/fafucoder/sriov-crd/pkg/apis/sriov/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// PFLister helps list PFs.
type PFLister interface {
	// List lists all PFs in the indexer.
	List(selector labels.Selector) (ret []*v1.PF, err error)
	// Get retrieves the PF from the index for a given name.
	Get(name string) (*v1.PF, error)
	PFListerExpansion
}

// pFLister implements the PFLister interface.
type pFLister struct {
	indexer cache.Indexer
}

// NewPFLister returns a new PFLister.
func NewPFLister(indexer cache.Indexer) PFLister {
	return &pFLister{indexer: indexer}
}

// List lists all PFs in the indexer.
func (s *pFLister) List(selector labels.Selector) (ret []*v1.PF, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.PF))
	})
	return ret, err
}

// Get retrieves the PF from the index for a given name.
func (s *pFLister) Get(name string) (*v1.PF, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("pf"), name)
	}
	return obj.(*v1.PF), nil
}
