/*
Copyright 2019 The Lijiao Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/fafucoder/sriov-crd/pkg/apis/sriov/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// SriovPFLister helps list SriovPFs.
type SriovPFLister interface {
	// List lists all SriovPFs in the indexer.
	List(selector labels.Selector) (ret []*v1.SriovPF, err error)
	// Get retrieves the SriovPF from the index for a given name.
	Get(name string) (*v1.SriovPF, error)
	SriovPFListerExpansion
}

// sriovPFLister implements the SriovPFLister interface.
type sriovPFLister struct {
	indexer cache.Indexer
}

// NewSriovPFLister returns a new SriovPFLister.
func NewSriovPFLister(indexer cache.Indexer) SriovPFLister {
	return &sriovPFLister{indexer: indexer}
}

// List lists all SriovPFs in the indexer.
func (s *sriovPFLister) List(selector labels.Selector) (ret []*v1.SriovPF, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.SriovPF))
	})
	return ret, err
}

// Get retrieves the SriovPF from the index for a given name.
func (s *sriovPFLister) Get(name string) (*v1.SriovPF, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("sriovpf"), name)
	}
	return obj.(*v1.SriovPF), nil
}
