apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pfs.kubeovn.io
spec:
  group: kubeovn.io
  version: v1
  scope: Cluster
  names:
    plural: pfs
    singular: pf
    kind: PF
    shortNames:
      - pf
  additionalPrinterColumns:
    - name: IfName
      type: string
      JSONPath: .spec.ifName
    - name: PfName
      type: string
      JSONPath: .spec.pfName
    - name: Node
      type: string
      JSONPath: .spec.nodeName
    - name: VfNum
      type: integer
      JSONPath: .spec.vfNum
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: vfs.kubeovn.io
spec:
  group: kubeovn.io
  version: v1
  scope: Cluster
  names:
    plural: vfs
    singular: vf
    kind: VF
    shortNames:
      - vf
  additionalPrinterColumns:
    - name: DeviceID
      type: string
      JSONPath: .spec.deviceID
    - name: PFName
      type: string
      JSONPath: .spec.pfName
    - name: PodName
      type: string
      JSONPath: .spec.podName
    - name: PodNamespace
      type: string
      JSONPath: .spec.podNamespace
    - name: NetName
      type: string
      JSONPath: .spec.netName
    - name: NodeName
      type: string
      JSONPath: .spec.nodeName